### ISSUE TITLE
Escaping rules for %gobuild extra options

### ISSUE THREAD

**Issue by matwey** [openSUSE/golang-packaging#17]
Hi,

I created an issue in BOO: https://bugzilla.opensuse.org/show_bug.cgi?id=1079998

The issue is that there is no way (in my opinion. probably there is some cryptic not obvious way) to pass `-ldflags="-X main.version=1.2.3"` as a single command line argument. It is important that we have to keep space between X and main.version and prevent `process_build` from rearranging arguments.

**Comment by cyphar** [comment]
Fixed by #16.
