### ISSUE TITLE
golang-packaging now Requires: rpmdevtools

### ISSUE THREAD

**Issue by moio** [openSUSE/golang-packaging#26]
This creates problems for SLE distributions, as they do not have that package.

A solution not relying on rpmdevtools would be desirable.

**Comment by SchoolGuy** [comment]
@moio I think this is outdated and can be closed?

Current version in the OBS doesn't require this anymore as far as I can see: https://build.opensuse.org/package/binary/openSUSE:Factory/golang-packaging/standard/i586/golang-packaging-15.0.15-1.4.src.rpm
